import Foundation

extension Curriculum {
    static let reliability = Chapter(
        id: "reliability", title: "7. Validation and a small analysis tool", subtitle: "Reject bad data and prove useful behavior", prerequisites: ["collections"],
        lesson: """
        # Make failure part of the contract

        So far, functions have been promised suitable inputs. Real data may violate those assumptions. **Validation** checks whether an input meets a contract before using it. The boundary is where data enters your function. A wrong type, a missing required field, or an out-of-range number should cause a clear failure rather than an invented result.

        An **exception** is an error signal that interrupts normal execution. You have seen names such as NameError and KeyError. `raise ValueError("message")` deliberately signals that an input is unacceptable. ValueError is an exception type; the string in parentheses is its explanation. Raising is not returning: the caller does not receive a normal result. Unless code catches the exception, Python stops and displays the error. Use a nonempty message that describes the problem.

        ## Check types before using operations

        `type(value)` returns a value's exact Python type. `type(value) is int` accepts an integer, not a float or Boolean. `is` compares identity; it is appropriate for exact type objects and None, not ordinary number or text comparisons (use `==` for those). `is not` means the identities differ. `isinstance(value, str)` asks whether value is a string, including a specialized subtype of string. Similarly, list and dict identify list and dictionary values.

        `in` tests membership and `not in` tests non-membership. In `type(value) not in (int, float)`, the parentheses hold a tuple of two accepted type objects, not quoted type names. The condition is true if the exact type is neither int nor float.

        The math module is part of Python. `import math` makes it available, and `math.isfinite(number)` returns True for a finite number, False for infinity or NaN (“not a number”). `float(value)` converts an accepted number to a float. Type checking must happen before operations that assume a number. Range checking can reject huge out-of-range integers before trying to convert them for a floating-point operation.

        ```python
        import math

        def checked_score(value):
            if type(value) not in (int, float):
                raise ValueError("score must be numeric")
            if not 0 <= value <= 1 or not math.isfinite(value):
                raise ValueError("score must be finite and between 0 and 1")
            return float(value)
        ```

        This block defines a function; calling `checked_score(0.5)` would return 0.5, while calling it with `'0.5'` would raise ValueError rather than converting the text. The `or` operator short-circuits: if its left condition is true, Python does not evaluate its right condition. `and` also short-circuits, stopping when its left condition is false. This lets validation avoid unsafe operations. For example, check that a value is text before calling a string method on it.

        Booleans deserve attention: `isinstance(True, int)` is True because bool is a subtype of int in Python. Exact type checks exclude them when measurements are required. Infinity is an unbounded floating-point value; NaN represents an undefined numeric result. They are not finite measurements. `float('inf')` and `float('nan')` create them for testing. NaN is not an ordinary ordered number, so do not rely only on a single lower-bound comparison.

        ## Catch an expected failure

        A `try` block contains an operation that may fail. A following `except ValueError as error:` block handles that specific exception and makes it available under the local name error. If no exception occurs, the except body is skipped. `str(error)` produces the message as text; `bool(text)` is False for empty text and True for nonempty text.

        ```python
        def require_positive(value):
            if type(value) is not int or value <= 0:
                raise ValueError("expected a positive integer")
            return value

        print(require_positive(3))
        try:
            require_positive(0)
        except ValueError as error:
            print(str(error))
        ```

        This prints 3, then expected a positive integer, and finishes normally because the error is caught. In validation exercises, your function should raise the error for the caller to handle, not catch its own error and return zero. Avoid a broad `except Exception`: it also catches unrelated programming errors and can turn broken code into apparently successful output.

        ## Validate formats, not just conversions

        `int(text)` accepts several numeric spellings, so conversion alone does not enforce a strict text format. First check the type, then remove permitted edge whitespace, then check membership in the allowed strings. For example, `choice in ('A', 'B')` permits just two exact strings. ASCII digits are the ordinary characters 0 through 9; other scripts can have digit characters that look similar but are different text. Python string escapes `\\t` and `\\n` represent a tab and a line break. strip removes these at the edges too, not inside the value.

        JSON parsing also has failure rules. `json.loads` raises `json.JSONDecodeError` for malformed JSON text; that exception is a kind of ValueError and already supplies a message. Successful parsing does not guarantee the shape you need: JSON `null` becomes None, `{}` becomes a dictionary, and `[]` becomes a list. A valid list can still contain invalid records. Check required dictionary fields and all items, including late ones; extra fields can be ignored only if the contract permits them.

        ## Tests are evidence, not validation code

        An `assert` states an expected property in a test. It is not a substitute for public input validation because Python can disable assertions. Test both successful results and expected exceptions. An exception test should fail if the operation unexpectedly succeeds.

        ```python
        def require_text(value):
            if not isinstance(value, str):
                raise ValueError("expected text")
            return value

        assert require_text("demo") == "demo"
        raised = False
        try:
            require_text(7)
        except ValueError as error:
            raised = bool(str(error))
        assert raised
        ```

        Both checks pass silently. The flag starts False and changes only when the expected error with a nonempty message occurs. Calling the function is essential: merely defining it does not test it. When repairing a function, follow its indentation: a return inside a loop ends the call before later records can be checked.

        ## Build a small trustworthy tool

        Separate parsing, validation, and aggregation in your reasoning, even when the final function is short. Define the empty-data result, whether extra keys are accepted, and whether the caller's data remains unchanged. When a regression appears, first add a minimal failing test, then repair the cause and rerun the suite. Your final assessment combines JSON input, complete record validation, and a deterministic summary. No network, external dependencies, or private data are necessary.
        """,
        exercises: [
            exercise("reliability-score", "Validate a confidence value", "Goal:\nAccept a numeric confidence score only when it fits a strict contract. A confidence score here is a finite number between 0 and 1, not text that happens to look numeric.\n\nStarting code:\ndef validate_score(value): is the required function. return 0.0 is a placeholder. You may add import math above the function to use Python's built-in math tools.\n\nYour task:\n1. Keep the function name and parameter. Accept only exact Python int or float values. Reject Booleans even though Python treats bool as an integer subtype. Do not convert strings into accepted scores.\n2. Accept both endpoints 0 and 1. Reject numbers below 0 or above 1, infinity, and NaN (not a number). Use math.isfinite as explained in the lesson, after checking that numeric operations are appropriate.\n3. Return each accepted score converted to a float, without rounding. For every rejected input, raise ValueError with any nonempty message instead of returning a fallback value. Do not modify the input.\n\nExamples:\nvalidate_score(0) returns 0.0.\nvalidate_score(1) returns 1.0 as a float.\nvalidate_score(0.75) returns 0.75.\nTrue, '0.5', None, [], -0.01, 1.01, NaN, infinities, and an enormous out-of-range integer must all raise ValueError.\n\nCheck:\nChoose Check solution. It checks accepted values and float output, then invalid types and numeric boundaries. Invalid cases must raise ValueError with a message, not TypeError or OverflowError.",
                     "def validate_score(value):\n    return 0.0\n",
                     "import math\n\ndef validate_score(value):\n    if type(value) not in (int, float):\n        raise ValueError('score must be numeric')\n    if not 0 <= value <= 1 or not math.isfinite(value):\n        raise ValueError('score must be finite and between 0 and 1')\n    return float(value)\n",
                     "assert validate_score(0) == 0.0\nassert type(validate_score(1)) is float\nassert validate_score(0.75) == 0.75\nfor invalid in [True, False, '0.5', None, [], -0.01, 1.01, float('nan'), float('inf'), -float('inf'), 10 ** 400]:\n    raised = False\n    try:\n        validate_score(invalid)\n    except ValueError as error:\n        raised = bool(str(error))\n    assert raised, 'invalid score must raise ValueError with a message'\n",
                     ["Reject unsuitable types before comparing ranges or calling numeric tools. A string method or numeric operation on the wrong type may raise an unintended exception.", "An exact type check distinguishes bool from int. Check the allowed range before math.isfinite so an enormous out-of-range integer cannot cause a float-conversion overflow; then exclude nonfinite values as well.", "Invalid input should interrupt the call with ValueError and a nonempty explanation. Only after all checks pass should the accepted number be converted to a float and returned."]),
            exercise("reliability-parse", "Parse an explicit retry setting", "Goal:\nRead a strict retry setting from text. A retry is another attempt after a failure; this setting chooses how many are permitted. Parsing means turning the accepted text into a useful value, not actually performing retries.\n\nStarting code:\ndef parse_retry_count(text): is the required function. return 0 is a placeholder. Tests provide both valid and invalid inputs.\n\nYour task:\n1. Keep the function name and parameter. Accept only strings whose content, after removing surrounding whitespace, is exactly one of '0', '1', '2', '3', '4', '5'. Edge spaces, tabs, and line breaks are allowed; do not remove internal characters.\n2. Return the corresponding integer from 0 through 5. Leave the original input unchanged.\n3. For every other input raise ValueError with any nonempty message. Reject non-strings, empty text, signs, decimal points, multiple digits such as '01', and non-ASCII digits (digit characters other than ordinary 0 through 9).\n4. Validate the allowed text before converting it; int alone accepts formats that this contract rejects.\n\nExamples:\nparse_retry_count('0') returns 0.\nparse_retry_count(' 5 ') returns 5.\nA tab, then '3', then a line break returns 3.\n'', '6', '-1', '+2', '01', '1.0', '１２', '²', integer 3, None, and True all raise ValueError.\n\nCheck:\nChoose Check solution. It checks accepted edge whitespace, integer output, and rejected spellings and types. A printed error or fallback zero does not satisfy the error contract.",
                     "def parse_retry_count(text):\n    return 0\n",
                     "def parse_retry_count(text):\n    if not isinstance(text, str):\n        raise ValueError('retry count must be text')\n    cleaned = text.strip()\n    if cleaned not in ('0', '1', '2', '3', '4', '5'):\n        raise ValueError('retry count must be a digit from 0 to 5')\n    return int(cleaned)\n",
                     "assert parse_retry_count('0') == 0\nassert parse_retry_count(' 5 ') == 5\nassert parse_retry_count('\\t3\\n') == 3\nassert type(parse_retry_count('2')) is int\nfor invalid in ['', ' ', '6', '-1', '+2', '01', '1.0', '１２', '²', 3, None, True]:\n    raised = False\n    try:\n        parse_retry_count(invalid)\n    except ValueError as error:\n        raised = bool(str(error))\n    assert raised, 'invalid retry setting must raise ValueError with a message'\n",
                     ["int can accept forms such as signed or multi-digit text, but this setting allows only six exact spellings. Conversion alone cannot enforce the contract.", "Check that the input is text before calling strip. Save a cleaned copy so edge whitespace is permitted without changing the caller's original value.", "Membership in a tuple of the six allowed strings can express the format rule. Convert to an integer only after that rule passes; rejected values need ValueError rather than a fallback result."]),
            exercise("reliability-summary", "Repair a latency summary", "Goal:\nRepair a function that summarizes durations. Latency is elapsed time; ms means milliseconds. Unlike the earlier missing-reading exercise, negative values here are invalid and must cause an error, not be skipped.\n\nStarting code:\ndef summarize_latencies(values): contains a deliberately faulty implementation. It adds to total, but its return is inside the loop and it performs no validation. Keep the function name and parameter; repair the body.\n\nYour task:\n1. Accept only a list whose every item is an exact Python integer at least zero. Reject Booleans, floats, and other item types. Zero is valid. Leave the list unchanged.\n2. Raise ValueError with any nonempty message for an invalid outer input or any invalid item, including an invalid item after valid ones.\n3. Return a dictionary with exactly 'count' (integer number of readings), 'total_ms' (integer sum), and 'mean_ms' (numeric arithmetic mean without rounding).\n4. For an empty list return {'count': 0, 'total_ms': 0, 'mean_ms': 0.0}. Ensure the final result accounts for every item, not only the first.\n\nExamples:\nsummarize_latencies([10, 0, 20]) returns {'count': 3, 'total_ms': 30, 'mean_ms': 10.0}.\nsummarize_latencies([7]) returns {'count': 1, 'total_ms': 7, 'mean_ms': 7.0}.\nNone, '12', the tuple (1, 2), [1, -1], [1, True], and [1, 2.0] must raise ValueError.\n\nCheck:\nChoose Check solution. It checks empty, single, and multiple readings, input preservation, and invalid outer types and later items. Return the dictionary; do not print it instead.",
                     "def summarize_latencies(values):\n    total = 0\n    for value in values:\n        total += value\n        return {'count': len(values), 'total_ms': total, 'mean_ms': total / len(values)}\n",
                     "def summarize_latencies(values):\n    if not isinstance(values, list):\n        raise ValueError('latencies must be a list')\n    total = 0\n    for value in values:\n        if type(value) is not int or value < 0:\n            raise ValueError('latencies must be nonnegative integers')\n        total += value\n    count = len(values)\n    return {'count': count, 'total_ms': total, 'mean_ms': total / count if count else 0.0}\n",
                     "assert summarize_latencies([]) == {'count': 0, 'total_ms': 0, 'mean_ms': 0.0}\nvalues = [10, 0, 20]\nassert summarize_latencies(values) == {'count': 3, 'total_ms': 30, 'mean_ms': 10.0}\nassert values == [10, 0, 20]\nassert summarize_latencies([7]) == {'count': 1, 'total_ms': 7, 'mean_ms': 7.0}\nfor invalid in [None, '12', (1, 2), [1, -1], [1, True], [1, 2.0], [1, '2']]:\n    raised = False\n    try:\n        summarize_latencies(invalid)\n    except ValueError as error:\n        raised = bool(str(error))\n    assert raised, 'invalid latencies must raise ValueError with a message'\n",
                     ["return ends the function call immediately. In the starter it runs during the first loop visit, so later readings are neither summed nor checked.", "Check that the outer input is a list before looping, then require every item to be an exact nonnegative integer. A valid first item does not make later items valid.", "The final report belongs after all visits. For the mean, an empty list needs its explicit 0.0 result rather than division by its zero length; nonempty input uses the full total and count."])
        ],
        assessment: exercise("reliability-assessment", "Analyze a synthetic evaluation file", "Goal:\nAnalyze invented model evaluation data and reject invalid input. An evaluation record describes one named model and its score. The title says file, but payload is supplied text: do not open any file or contact a service.\n\nStarting code:\nimport json and def analyze_evaluations(payload): are supplied. return {} is a placeholder. Keep the function name and parameter; use only Python's standard library.\n\nYour task:\n1. Accept only a string containing JSON whose top-level value is a list. Every list item must be an object with both 'model' and 'score' fields. Leave the supplied input unchanged.\n2. model must be a string containing at least one non-whitespace character. score must have exact Python type int or float, not bool, be finite, and lie between 0 and 1 inclusive. Extra object fields are allowed and ignored.\n3. Any invalid input, malformed JSON, wrong shape, missing required field, or invalid record must raise ValueError with a nonempty message. This applies even if earlier records were valid. Do not return a partial summary.\n4. Return a Python dictionary with exactly these keys: 'count', the integer number of records; 'passed', the integer number with scores at least 0.8, including exactly 0.8; 'mean_score', the unrounded numeric arithmetic mean of all scores; and 'models', a list of distinct model-name strings without edge whitespace, sorted in Python's normal ascending string order. Preserve name case and internal whitespace; repeated cleaned names appear only once in models but their records still contribute to all numeric results.\n5. An empty array returns {'count': 0, 'passed': 0, 'mean_score': 0.0, 'models': []}. Return Python data, not JSON text or printed output.\n\nExamples:\nFor '[{\"model\":\" orbit \",\"score\":0.8},{\"model\":\"Nova\",\"score\":0},{\"model\":\"orbit\",\"score\":1,\"tag\":\"synthetic\"}]', return {'count': 3, 'passed': 2, 'mean_score': 0.6, 'models': ['Nova', 'orbit']}.\nFor '[{\"model\":\"a\",\"score\":0.79}]', passed is 0.\nNone, empty text, '{', '{}', 'null', '[1]', '[{}]', blank model names, Boolean or string scores, out-of-range scores, NaN, and infinities must raise ValueError.\n\nCheck:\nComplete the theory questions and written explanation, then choose Submit assessment. It checks valid and empty summaries, exact keys, the passing boundary, unique sorted names, and invalid inputs including a bad record after a valid one. Work independently without hints or solutions.",
                             "import json\n\ndef analyze_evaluations(payload):\n    return {}\n",
                             "import json\nimport math\n\ndef analyze_evaluations(payload):\n    if not isinstance(payload, str):\n        raise ValueError('payload must be JSON text')\n    records = json.loads(payload)\n    if not isinstance(records, list):\n        raise ValueError('payload must contain a list')\n    total = 0.0\n    passed = 0\n    models = set()\n    for record in records:\n        if not isinstance(record, dict):\n            raise ValueError('each record must be an object')\n        model = record.get('model')\n        score = record.get('score')\n        if not isinstance(model, str) or not model.strip():\n            raise ValueError('model must be nonempty text')\n        if type(score) not in (int, float):\n            raise ValueError('score must be numeric')\n        if not 0 <= score <= 1 or not math.isfinite(score):\n            raise ValueError('score must be finite and in range')\n        models.add(model.strip())\n        total += score\n        if score >= 0.8:\n            passed += 1\n    count = len(records)\n    return {'count': count, 'passed': passed, 'mean_score': total / count if count else 0.0, 'models': sorted(models)}\n",
                             "assert analyze_evaluations('[]') == {'count': 0, 'passed': 0, 'mean_score': 0.0, 'models': []}\nreport = analyze_evaluations('[{\"model\":\" orbit \",\"score\":0.8},{\"model\":\"Nova\",\"score\":0},{\"model\":\"orbit\",\"score\":1,\"tag\":\"synthetic\"}]')\nassert set(report) == {'count', 'passed', 'mean_score', 'models'}\nassert report['count'] == 3 and report['passed'] == 2\nassert abs(report['mean_score'] - 0.6) < 1e-10\nassert report['models'] == ['Nova', 'orbit']\nassert analyze_evaluations('[{\"model\":\"a\",\"score\":0.79}]')['passed'] == 0\nfor invalid in [None, b'[]', '', '{', '{}', 'null', '[1]', '[{}]', '[{\"model\":\" \",\"score\":0.5}]', '[{\"model\":3,\"score\":0.5}]', '[{\"model\":\"a\",\"score\":true}]', '[{\"model\":\"a\",\"score\":\"0.5\"}]', '[{\"model\":\"a\",\"score\":-0.1}]', '[{\"model\":\"a\",\"score\":1.1}]', '[{\"model\":\"a\",\"score\":NaN}]', '[{\"model\":\"a\",\"score\":Infinity}]', '[{\"model\":\"ok\",\"score\":1},{\"model\":\"bad\"}]']:\n    raised = False\n    try:\n        analyze_evaluations(invalid)\n    except ValueError as error:\n        raised = bool(str(error))\n    assert raised, 'invalid payload must raise ValueError with a message'\n",
                             []),
        quiz: [
            question("reliability-q1", "Why can isinstance(value, int) accidentally accept a Boolean score?", ["All strings are integers", "bool is a subclass of int", "JSON has no Booleans"], 1, "Python treats bool as an int subclass; an exact type check excludes True and False."),
            question("reliability-q2", "Why avoid except Exception: return 0 around an entire analysis?", ["It can hide bugs and report invalid data as success", "Exceptions cannot be caught", "It makes all calculations nondeterministic"], 0, "Catch only expected failures you can handle; a fabricated zero hides the reason analysis failed."),
            question("reliability-q3", "Which test exposes validation that stops after the first valid record?", ["An empty array only", "One valid record", "A valid record followed by an invalid one"], 2, "A later invalid record ensures the function traverses and validates the entire input.")
        ])
}
